name: Local-test

on: 
 workflow_dispatch:

jobs:
   Build-All-Endpoints:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Clone Food
      run: git clone https://github.com/soat-order/soat-order-food.git
    - name: Build Food
      run: cd ./soat-order-food/ci/; docker-compose -f "docker-compose-local.yml" up -d --build
    - name: Test Food
      run: |
        sleep 30; docker ps; curl -v --request GET --url http://localhost:8000/soat-order-food/v1/health/actuator --header 'Content-Type: application/json' --header 'User-Agent: insomnia/8.6.1'
      
    - name: Clone Status
      run: git clone https://github.com/soat-order/soat-order-status.git
    - name: Build Status
      run: cd ./soat-order-status/ci/; docker-compose -f "docker-compose-local.yml" up -d --build
    - name: Test Status
      run: |
        sleep 30; docker ps; curl -v --request GET --url http://localhost:8002/soat-order-status/v1/health/actuator --header 'User-Agent: insomnia/8.6.1'
      
    - name: Clone Payment
      run: git clone https://github.com/soat-order/soat-order-payment.git
    - name: Build Payment
      run: cd ./soat-order-payment/ci/; docker-compose -f "docker-compose-local.yml" up -d --build
    - name: Test Payment
      run: |
        sleep 30; docker ps; curl -v --request GET --url http://localhost:8001/soat-order-payment/v1/health/actuator --header 'User-Agent: insomnia/8.6.1'

    - name: Autenticar
      run: |
        curl --request POST --url http://localhost:8000/soat-order-food/v1/auth/singup --header 'Content-Type: application/json' --data '{"username": "soat.order",	"password": "food",	"email": "soat.order@fiap.com.br"}'
        curl --request POST --url http://localhost:8000/soat-order-food/v1/auth/login/token --header 'Authorization: Basic c29hdC5vcmRlcjpmb29k'
        curl --request POST --url http://localhost:8000/soat-order-food/v1/auth/login/token --header 'Authorization: Basic c29hdC5vcmRlcjpmb29k'

    - name: Cadastrar e Ativar Cliente
      run: |
        curl --request POST --url http://localhost:8000/soat-order-food/v1/customers/ --header 'Content-Type: application/json' --data '{"name": "FIAP 1",	"documentNumber": "000.000.000-00",	"email": "soat.order@fiap.com.br",	"phoneNumber": "19912345678"}'
        sleep 5
        response=$(curl -s --request GET --url http://localhost:8000/soat-order-food/v1/customers/ --header "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiSFMyNTYiLCJleHAiOjE3MTIyMTEwNzksImlhdCI6MTcxMjIwNzQ3OSwic3ViIjoic29hdC5vcmRlcnw2MjUwNmJlMy00ZDU3LTRkYTQtYTBkMS01OGE2NzI1M2VhOTkifQ.AhP3199eLLdXjzPjitx4qiaYjwv3vRgbUgCm_YnoN5Q")
        desired_name="FIAP 1"
        id=$(echo "$response" | jq -r --arg desired_name "$desired_name" '.data[] | select(.name == $desired_name) | .id')
        echo "Cliente cadastrado $desired_name: $id"
        curl --request PUT --url http://localhost:8000/soat-order-food/v1/customers/$id/inactive --header 'Content-Type: application/json' --data '{"inactive": false}'
        
    - name: Cadastrar e Ver Produtos
      run: |
        curl --request POST --url http://localhost:8000/soat-order-food/v1/products/ --header 'Content-Type: application/json' --data '{"code": "COCA350",	"name": "COCA COLA LATA 350ML",	"amount": 6.00,	"type": "BEBIDA"}'
        sleep 5
        curl --request GET --url http://localhost:8000/soat-order-food/v1/products/

    - name: Fazer e Ver Pedidos
      run: |
        curl --request POST --url http://localhost:8000/soat-order-food/v1/orders/ --header 'Content-Type: application/json' --data '{"customerName": "FIAP 01",	"customerIdentify": "000.000.000-00",	"items": [{"productCode": "COCA350", "quantity": 1.00, "note": "TEMPERATURA AMBIENTE"}]}'
        sleep 5
        response=$(curl -s --request GET --url http://localhost:8000/soat-order-food/v1/orders/)
        echo $response
        orderId=$(echo "$response" | jq -r '.data[].id')

    - name: Realizar pagamento
      run: |
        curl -s -v --request POST --url http://localhost:8001/soat-order-payment/v1/payments/ --header 'Content-Type: application/json' --data "{\"orderId\": \"$orderId\", \"payments\": [{\"type\": \"CREDIT_CARD\", \"amountPaid\": 15.00}, {\"type\": \"MONEY\", \"amountPaid\": 2.00}]}"

    - name: Atualização de Status por pagamento
      run: |
        sleep 5
        response=$(curl -s --request GET --url http://localhost:8000/soat-order-food/v1/orders/)
        echo $response
        status=$(echo "$response" | jq -r '.data[].status')
        echo "Pedido atualizado para $status em decorrência do pagamento realizado"

    - name: Atualização de Status para em Preparação
      run: |
        curl --request PUT --url http://localhost:8000/soat-order-food/v1/orders/$orderId/status/in_preparation/
        sleep 5
        response=$(curl -s --request GET --url http://localhost:8000/soat-order-food/v1/orders/)
        echo $response
        status=$(echo "$response" | jq -r '.data[].status')
        echo "Cozinha alterou o status para $status"

    - name: Atualização de Status para Finalizado
      run: |
        curl --request PUT --url http://localhost:8000/soat-order-food/v1/orders/$orderId/status/finished/
        sleep 5
        response=$(curl -s --request GET --url http://localhost:8000/soat-order-food/v1/orders/)
        echo $response
        status=$(echo "$response" | jq -r '.data[].status')
        echo "Cozinha alterou o status para $status"

    - name: Cliente solicitou exclusão de cadastro
      run: |
        curl --request PUT --url http://localhost:8000/soat-order-food/v1/customers/$id/inactive --header 'Content-Type: application/json' --data '{"inactive": true}'
        sleep 5
        curl -s --request GET --url http://localhost:8000/soat-order-food/v1/customers/ --header "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiSFMyNTYiLCJleHAiOjE3MTIyMTEwNzksImlhdCI6MTcxMjIwNzQ3OSwic3ViIjoic29hdC5vcmRlcnw2MjUwNmJlMy00ZDU3LTRkYTQtYTBkMS01OGE2NzI1M2VhOTkifQ.AhP3199eLLdXjzPjitx4qiaYjwv3vRgbUgCm_YnoN5Q"

        
        
        


        
