name: Local-test

on: 
 workflow_dispatch:

jobs:
   Build-All-Endpoints:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Clone Food
      run: git clone https://github.com/soat-order/soat-order-food.git

    - name: Build Food
      run: cd ./soat-order-food/ci/; docker-compose -f "docker-compose-local.yml" up -d --build

    - name: Test Food
      run: |
        docker ps; curl --request GET --url http://localhost:8000/soat-order-food/v1/health/actuator --header 'Content-Type: application/json' --header 'User-Agent: insomnia/8.6.1'
      
    - name: Clone Status
      run: git clone https://github.com/soat-order/soat-order-status.git

    - name: Build Status
      run: cd ./soat-order-status/ci/; docker-compose -f "docker-compose-local.yml" up -d --build

    - name: Clone Payment
      run: git clone https://github.com/soat-order/soat-order-payment.git

    - name: Build Payment
      run: cd ./soat-order-payment/ci/; docker-compose -f "docker-compose-local.yml" up -d --build
